### ISSUE TITLE
feature request: experimental appimage for linux kernel modules

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/VirtualBox-appimage#1]
for examples：
display-link module：evdi
vmware module：

if the kernel modules merge in appimage that were great operate

**Comment by ivan-hc** [comment]
this is based on Conty, no kernel modules can work on it, this is why I've based it on VirtualBox KVM. Please, see the README

**Comment by ivan-hc** [comment]
AppImages are not ment to use kernel modules, nor ment to run as root
