### ISSUE TITLE
cannot open host folder

### ISSUE THREAD

**Issue by Dex94** [ivan-hc/VirtualBox-appimage#11]
![a](https://github.com/user-attachments/assets/26400189-5348-4f97-bab6-1abb31f953e1)
I need to move vm to host folder but it's not present. I tried to edit vbox file to move manually the vm folder but it doesn't recognize the destination and it gives an error, as if that folder didn't exist

**Comment by ivan-hc** [comment]
hi, can you be more specific? What exactly do you need to do? can you show me the error message? have you tried running virtualbox from terminal to see the error messages? I need more details.

**Comment by Dex94** [comment]
file manager of virtualbox hides hr hard disk whre it's installed linux. That hard disk isn'y mounted in/media/user folder but it's mounted as a folder named host and its address is /host. It isn't possible to use it because virtualbox doesn't show it. I tried to start  from terminal virtualbox but there isnn't any error 
![b](https://github.com/user-attachments/assets/95e806b3-5bf7-4427-864d-d788b27941a6)
![c](https://github.com/user-attachments/assets/bd092704-d4d2-4278-bd2d-b8224cc56630)
as you can see creating/moving a virtual machine opens a window. Going to / path there isn't host folder (hard disk where it's installed linux). I tried to ln -s /host to my user path /home but it doesn't work

**Comment by ivan-hc** [comment]
oh, then you have an extra directory in the root named /host, this means that the container can't see it.

This AppImage is based on an Arch Linux container that uses bubblewrap to mount directories on the host if the same are in the structure of directories inside the containjer itself.

For example, I have my VMs in /media, and being it a commonly used directory, it can be mounted from the container.

I can't do much in this regard. Building these containers in AppImage does not allow for the existence of directories outside the schema (Linux Standard Base). This is a limitation of bubblewrap mounted containers. I would have to include a command to mount your directory specifically (I would have to create an empty one in the AppImage and do `--bind-try /host /host`), but if I do this with you I would have to do it with everyone who has alternately named directories in the filesystem, and that's bad.

Did you create this directory? Or is it on an alternate filesystem?

Creating a symbolic link would be the only solution for that specific directory, but if that doesn't work, I recommend using a different directory.

**Comment by Dex94** [comment]
> Did you create this directory? Or is it on an alternate filesystem?
No I didn't. see this: https://wiki.ubuntu.com/WubiGuide 
> Creating a symbolic link would be the only solution for that specific directory, but if that doesn't work, I recommend using a different directory.
I tried but nothing.

**Comment by ivan-hc** [comment]
> > Did you create this directory? Or is it on an alternate filesystem?
> 
> No I didn't. see this: https://wiki.ubuntu.com/WubiGuide

I haven't heard of Wubi in over 10 years, so does it still exist?

So you are using VirtualBox AppImage on Wubi/Windows. Now it makes sense.

> > Creating a symbolic link would be the only solution for that specific directory, but if that doesn't work, I recommend using a different directory.
> 
> I tried but nothing. I can share two mount points. /dev/sda1 /host fuseblk rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096 0 0 /dev/sdb1 /media/user/Volume fuseblk rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096 0 0
> 
> when a ntfs volume is mounted it can't be mounted twice. The problem is not to create the vm in another volume but also to retrieve all the files I need in the disk not displayed

Look, at this point I don't know what to suggest, VirtualBox is something that normally works at the kernel level, and it's a lot to be able to implement it in an AppImage. The problem is that bubblewrap doesn't recognize this directory structure.

Fork this repository, I'll tell you what you need to add to the script to create and test an AppImage that suits your needs.

**Comment by ivan-hc** [comment]
well, now copy the content of these two files in the related .sh files with the same name (I had to add .txt as an extension because .sh are not allowed in comments on github)

[create-arch-bootstrap.sh.txt](https://github.com/user-attachments/files/17050156/create-arch-bootstrap.sh.txt)
[virtualbox-conty-builder.sh.txt](https://github.com/user-attachments/files/17050157/virtualbox-conty-builder.sh.txt)

in create-arch-bootstrap.sh I added `mkdir -p "${bootstrap}"/host` at line 448, while in `virtualbox-conty-builder.sh.txt` I have changes this
```
CONTY_CMD="${HERE}/conty.sh --bind-try /usr/share/fonts /usr/share/fonts"
```
with this
```
CONTY_CMD="${HERE}/conty.sh --bind-try /usr/share/fonts /usr/share/fonts --bind-try /host /host"
```
when you have finished, run the github action workflow named "Release VirtualBox Appimage" (file is CI.yml).

The process take about 5 minutes.

At the end download the AppImage from your "releases" rection.

**Comment by ivan-hc** [comment]
It should work, but let me know if it works for you.

**Comment by Dex94** [comment]
thank you very much. Solved and now i can see the folder
![d](https://github.com/user-attachments/assets/fc6e6284-a882-4b80-9f22-ae037f5b93b0)

**Comment by ivan-hc** [comment]
take a look here https://www.reddit.com/r/virtualbox/comments/11qm6x0/manjaro_on_virtualbox_critical_error/

**Comment by Dex94** [comment]
I tried to use the same vm with virtualbox installed, no problem, then I tried with appimage and it crashes. Maybe it's a appimage problem but I don't know what to do

**Comment by ivan-hc** [comment]
the AppImage is based on VirtualBox KVM, it does not require kernel modules and drivers installed to work, but it is still experimental and needs improvements. I have built it from AUR

**Comment by Dex94** [comment]
the only difference I see in the settings is that in the appimage the option to activate nested vtx /amd-v is obfuscated and it can't be enabled, in the installed virtualbox it's available. So I think there's a lack of support for amd cpu.

**Comment by ivan-hc** [comment]
> the only difference I see in the settings is that in the appimage the option to activate nested vtx /amd-v is obfuscated and it can't be enabled, in the installed virtualbox it's available. So I think there's a lack of support for amd cpu.

just noticed, thank you

I think that this is still an issue with the container. VirtualBox needs to be installed system wide with its kernel modules, and the AppImage does not work like this. AppImage needs to be portable. I I had not known VirtualBox KVM, it was still impossible to create the AppImage.

**Comment by ivan-hc** [comment]
for example, "vboxdrv" is not needed in this version of VirtualBox, normal VirtualBox needs it to made you run virtual machines.

**Comment by ivan-hc** [comment]
try to extract the appimage
```
./*.AppImage --appimage-extract
```
enter the directory and run this command
```
./conty.sh virtualbox
```
you will see the "vboxdrv" message "uncensored" (I hide it because it is not needed in virtualBox KVM)
