### ISSUE TITLE
Handler to download Guest Additions: suggestions?

### ISSUE THREAD

**Issue by ivan-hc** [ivan-hc/VirtualBox-appimage#4]
I'm investigating on missing libraries or packages to allow the installation of  Guest Additions.

Can someone of you point me in the right way?

Thanks in advance.

**Comment by in4matix** [comment]
Hi Ivan,
Firstly thank you very much for this work.
I am not knowledgeable enough about coding and libraries, but can you not maybe include in your script to include the extensions pack?   https://download.virtualbox.org/virtualbox/7.0.20/Oracle_VM_VirtualBox_Extension_Pack-7.0.20.vbox-extpack
Also, this version claims to not require any other libraries, might be worth looking into?
https://download.virtualbox.org/virtualbox/7.0.20/VirtualBox-7.0.20-163906-Linux_amd64.run

**Comment by ivan-hc** [comment]
I fixed this in https://github.com/ivan-hc/VirtualBox-appimage/commit/051124bdfe2f9fc4c807d26a80300e84d3c0721a

Next release will have guest addition iso
