### ISSUE TITLE
the options not work

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/VirtualBox-appimage#5]
![image](https://github.com/user-attachments/assets/b5596b1d-0af6-4d95-a6af-a7c63b91cad1)

**Comment by ivan-hc** [comment]
have you tested all of them?

**Comment by ivan-hc** [comment]
tell me what are the ones you see are useless, I'll remove them

I've just tested
```
virtualbox VirtualBoxVM --comment "Debian Stable" --startvm {VM_LONG_ID...}
```
and worked

**Comment by newyorkthink** [comment]
![image](https://github.com/user-attachments/assets/4a53a3b6-00ca-4eb1-9701-697a3afce8c7)

**Comment by newyorkthink** [comment]
it work

**Comment by newyorkthink** [comment]
but some argu not work

**Comment by ivan-hc** [comment]
> but some argu not work

ok, let me know what I must remove

**Comment by newyorkthink** [comment]
> > but some argu not work
> 
> ok, let me know what I must remove

i think the virtualbox argu is diffirent
![image](https://github.com/user-attachments/assets/5ee19ca8-1278-4157-aaf5-55b444b43cc3)

**Comment by newyorkthink** [comment]
some virtalbox-kvm argu and diffirence for the oracle virtualbox
