### ISSUE TITLE
the all argu allow redirection startvm

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/VirtualBox-appimage#6]
![Peek 2024-07-31 13-39](https://github.com/user-attachments/assets/21162b53-2365-49be-bbec-c97e62c6d5f5)
![image](https://github.com/user-attachments/assets/301f0a2b-1152-4a6c-acfb-a1c98c834b7b)

when i wan to power off it it just allow start win10

and other argu that redirect startvm too

**Comment by newyorkthink** [comment]
```
#!/bin/bash

# Virtual machine name
VM_NAME="win10"

# Start the virtual machine using VirtualBoxVM
virtualbox VirtualBoxVM --startvm "$VM_NAME"
if [ $? -eq 0 ]; then
  echo "Virtual machine $VM_NAME started successfully."
else
  echo "Failed to start virtual machine $VM_NAME."
fi
```

this is simple shell script for me.

**Comment by ivan-hc** [comment]
I have not understand the issue

**Comment by newyorkthink** [comment]
> I have not understand the issue
I mean all the commands in virtualbox point to startvm

**Comment by newyorkthink** [comment]
I mean all the commands in virtualbox point to startvm

**Comment by newyorkthink** [comment]
Other command parameters for virtualbox are invalid

**Comment by ivan-hc** [comment]
as i said in the other issue, list all commands I can remove, so I'll remove them.
