### ISSUE TITLE
feature request: add expect pack

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/VirtualBox-appimage#9]
hi, ivan
i find this extention pack
https://aur.archlinux.org/packages?O=0&SeB=nd&K=virtualbox-ext&outdated=&SB=p&SO=d&PP=50&submit=Go
https://archlinux.org/packages/extra/x86_64/virtualbox-ext-vnc/

can you merge into your virtualbox appimage

thank in advance

**Comment by ivan-hc** [comment]
what is the purpouse of the VNC pack?

**Comment by newyorkthink** [comment]
> what is the purpouse of the VNC pack?

vnc is support virtualbox can connect remote desktop

**Comment by newyorkthink** [comment]
like remmina
![image](https://github.com/user-attachments/assets/71100635-210a-4c6e-b88f-d660fbda3f27)

**Comment by in4matix** [comment]
@Samueru-sama just install VNC server on guest..?

**Comment by ivan-hc** [comment]
> @Samueru-sama just install VNC server on guest..?

@in4matix I think you wanted to say @newyorkthink , not @Samueru-sama (that is not a VirtualBox user at all).

Anyway, if to install a VNC server in the guest system is already a solution, I don't think that it is necessary to add also VNC as an extension, I have read that this is something provided by package managers of distributions, and that Oracle does not recognize them.

So, @newyorkthink , as just said... is it to install VNC server on the guest the same thing?

**Comment by in4matix** [comment]
@ivan-hc yes, sorry, typo.

@newyorkthink I assume you want to access the guest via remote viewer like with Qemu / KVM (Virt-Viewer) ? If so, the best way is to install VNC / RDP server on the guest. A very good solution is NoMachine which also allow us to access devices, etc on the guest.

**Comment by newyorkthink** [comment]
@ivan-hc did you can be create new repost for vmware-workstation， it can built
https://aur.archlinux.org/packages/vmware-workstation

i built it successful, but cannot run vm, just run gui

**Comment by newyorkthink** [comment]
just simple for this
export packagelist="${audio_pkgs} libpng gnutls openal \
	which ttf-dejavu ttf-liberation xorg-xwayland wayland \
	xorg-server xorg-apps curl  v4l-utils \
 	kvantum kvantum-qt5 qt5ct qt6ct libva sdl2 vulkan-icd-loader \
        vmware-workstation"

**Comment by ivan-hc** [comment]
@newyorkthink see the error messages in your terminal. I'm sure that its an issue with kernel modules.

Again, Virtualbox KVM is NOT a normal Virtualbox, and Gnome Boxes is already more portable tha others.

About Vmware, Quemu and other virtualization solutions, I DON'T KNOW NOTHING!

So please, don't ask me working on things I don't know.

I already have more than 70 AppImages, and not all are 100% working as they should. Also Virtualbox.

I have no intention of taking on the responsibility of making things work that I don't know about.

@newyorkthink if you plan to build it yourself, open your own repository and tag me in an issue, I'll be happy to collaborate.

I can't go any further.

----------------------------------------------

Finally, the focus of this issue has alerady been answered by @in4matix

I can close this issue.
